<h2>INSANITY: THE ASYLUM® Challenge Pack</h2>

<p>Shaun T increases your fitness and performance in just 30 days so you can feel like a pro! Sports-specific training and progressive drills build your speed, coordination, and power.</p>

<p class="bold">Your Challenge Pack also includes:</p>

<ul>
<li>Your first 30-day supply of Shakeology®—The Healthiest Meal of the Day®, delivered through Home Direct, our autoship program that ensures timely delivery of Shakeology to your doorstep every month.*</li>
<li>A FREE 30-day trial membership in the Team Beachbody® Club, where you’ll find all the support you’ll need to complete your Challenge.**†</li>
<li>Plus FREE standard shipping!</li>
</ul>

<p>Shakeology Chocolate + Greenberry Combo available in single-serving packets only.</p>

<p class="bold">Maximize your sports performance in just 30 days.</p>

<p>Shaun T developed these 6 intense workouts based on elite athletic training. You’ll drill intensely to improve your speed, coordination, agility, and strength. So on game day, you’ll have the unbeatable athletic edge.</p>

<p>Here’s what your Challenge Pack includes:</p>

<p class="bold">6 Intense Workouts:</p>

<ul>
<li>01 Speed & Agility</li>
<li>02 Vertical Plyo</li>
<li>High & Tight – Focus on your hips and lift your glutes. (35 minute</li>
<li>03 Relief</li>
<li>04 Strength</li>
<li>05 Game Day</li>
<li>06 Back to Core</li>
</ul>

<ul>
<li><span class="boldTitle">Agility Ladder.</span> This portable ladder helps you sharpen your focus and form.</li>
<li><span class="boldTitle">Speed Rope.</span> This tool is the secret to improving your foot speed and endurance.</li>
<li><span class="boldTitle">Get Shredded Nutritional Plan. </span> Follow Shaun T’s meals and tips to feel fit and ready from the inside out.</li>
<li><span class="boldTitle">Guide Playbook.</span>  Map out your 30-day transformation with this smart step-by-step manual.</li>
<li><span class="boldTitle">ASYLUM Workout Calendar.</span>   Check the calendar each day to cross-train like a professional athlete.</li>
<li><span class="boldTitle">Online Support.</span>  Stay inspired with round-the-clock access to fitness experts and peer support</li>
<li><span class="boldTitle">Two bonus workout DVDs.</span>  Sports Performance Assessment and Overtime.</li>
<li><span class="boldTitle">Exclusive Power Bands</span>  Tintermediate and advanced levels! Available on Team Beachbody®</li>
</ul>


<p class="bold">Plus</p>

<p class="bold">A 30-Day Supply of Shakeology—The Healthiest Meal of the Day.</p>
<p>OSimplify your nutrition with the convenient daily shake that helps you increase energy, become more regular, lose weight, and feel great. A combination of antioxidants, phytonutrients, adaptogens, and many other rare ingredients give your body the essential nutrients you can’t get from a normal diet. You get a salad bowl’s worth of fruits and vegetables in a single glass. 100% vegan option now available.‡</p>


<p class="bold">PLUS:</p>
<p class="bold">FREE 30-Day Trial Membership in the Team Beachbody Club.**†</p>
<p>When you’re part of the Team Beachbody community, you have all the tools, support, and accountability you need to commit to a healthy lifestyle, including:</p>
<ul>
<li>10% discount on all purchases</li>
<li>Meal plans personalized for your goals</li>
<li>VIP access to your favorite trainers and Beachbody® experts, including live chats, exclusive videos, nutrition tips, and delicious recipes</li>
<li>Your own personal Coach for guidance and support</li>
<li>Access to SuperGym®, where you can win cash or prizes just for logging your workouts every day</li>
<li>Message boards and chat rooms to help you find new friends and workout partners, and get advice and support from the entire community</li>
</ul>


<p class="bold">30-Day Money-Back Guarantee</p>
<p>We’re so sure you’ll love this Challenge Pack, we’re giving you our 30-day money-back guarantee. If you’re not completely satisfied, simply call Customer Service to return it within 30 days for a refund of the purchase price (less any S&H).</p>


<p class="price">$180.00</p>
<button><a href="http://teambeachbody.com/shop/-/shopping?referringRepId=416555">Buy Now</a></button>


<iframe class="videoWorkout" width="350" height="263" src="http://www.youtube.com/embed/GbZWQq7ek_w" frameborder="0" allowfullscreen></iframe>