<h2>P90X2® Foam Roller</h2>

<p class="bold">Specially designed for self-myofascial release, an intense form of sports massage. It can help reduce muscle and joint pain and enhance your athletic performance.</p>

<p>You can punch harder by engaging more muscles in your arms, and incinerate calories like crazy when you do your workouts wearing LES MILLS COMBAT Training Gloves.</p>

<p class="bold">Foam Roller:</p>

<ul>
<li>Regular use can help reduce muscle and joint pain for better mobility</li>
<li>Size: 31 inches</li>
</ul>


<p class="price">$29.95</p>
<button><a href="http://teambeachbody.com/shop/-/shopping/FoamRoller?referringRepId=416555">Buy Now</a></button>