<h2>Focus T25</h2>

<p>Get an hour's results in 25 minutes a day! Trainer Shaun T gives you everything you need, nothing you don't. 25 minutes. 5 days a week. 100% results.</p>

<p class="bold">25 Minutes. 5 Days a Week. 100% Results.</p>

<p>The only thing standing between you and the results you want is TIME. Shaun T experimented for the last year to design a program that delivers the same kind of results you'd expect from an hour-long program, in under 30 minutes. He's pulled out the rest to give you everything you need, nothing you don't. The result is FOCUS T25—and the name implies the intent: If you focus your intensity for 25 minutes, and you do it 5 days a week, you WILL get results.</p>

<p>Your FOCUS T25 program includes:</p>

<p class="bold">ALPHA Cycle 25-Minute Workouts:</p>

<ul>
<li><span class="boldTitle">Cardio.</span> 25 minutes of calorie-burning, sweat-drenching cardio.</li>
<li><span class="boldTitle">Speed 1.0.</span> Ignite your quickness. Burn the fat. Fast-paced for fast results.</li>
<li><span class="boldTitle">Total Body Circuit.</span> Focus on strength and resistance—without lifting a single weight.</li>
<li><span class="boldTitle">Ab Intervals.</span> Cardio and ab intervals that shred the fat from your midsection.</li>
<li><span class="boldTitle">Lower Focus.</span>  Focus on your lower-body muscles—the key to burning fat and kicking up your metabolism.</li>
</ul>

<p>BETA Cycle 25-Minute Workouts:</p>

<li><span class="boldTitle">Core Cardio. </span> Get your sweat on! This progressive cardio-core workout is about you getting shredded fast.</li>
<li><span class="boldTitle">Speed 2.0.</span> Rev it up with Shaun's calorie-scorching, core-focused speed drills.</li>
<li><span class="boldTitle">Rip't Circuit.</span> Cardio … upper body … legs … abs ... repeat! This is how you get ripped in 25 minutes.</li>
<li><span class="boldTitle">Dynamic Core.</span> You'll go from vertical to horizontal and back again in this dynamic, crazy core routine.</li>
<li><span class="boldTitle">Upper Focus.</span> Shaun will help you develop the upper body of your dreams. All you have to do is FOCUS.</li>
</ul>

<p>Tools to Make Every Minute Count:</p>

<ul>
<li><span class="boldTitle">Quick-Start Guide.</span> Hit the ground running with this step-by-step guide for how to achieve your best results.</li>
<li><span class="boldTitle">Get It Done Nutrition Guide.  </span> We make eating simple too! 5 meals a day, 5 ingredients, 5 minutes to prep. It's that simple.</li>
<li><span class="boldTitle">ALPHA-BETA Workout Calendars. </span> Shaun gives you each day's workout so there's no guesswork. All you have to do is nail it!</li>
</ul>

<p>Plus, 4 FREE Gifts:</p>
<ul>
<li><span class="boldTitle">Stretch Workout.</span> After 5 days of hard work, stretch it out—and enjoy this one! You deserve it.</li>
<li><span class="boldTitle">5-Day Fast Track.  </span> Get a jump start on your weight loss with this 5-day meal plan. It's not easy but it works!</li>
<li><span class="boldTitle">B-LINES® Resistance Band (15 lb.). </span> Burn fat and carve lean muscle faster with our lightweight pro-grade resistance band.†</li>
<li><span class="boldTitle">24/7 Online Support. </span> Stay motivated with 'round-the-clock access to fitness experts and peer support.</li>
</ul>

<p>And a FREE Bonus Workout:</p>
<ul>
<li><span class="boldTitle">Core Speed.</span> Push hard, burn fat, and get shredded in record time with the FREE bonus workout DVD Core Speed (a $19.95 value) when you order FOCUS T25 through your Coach or Team Beachbody®.
</li>
</ul>


<p class="bold">30-Day Money-Back Guarantee:</p>
<p>Shaun's so sure you'll get amazing results with FOCUS T25, he's giving you a 30-day money-back guarantee. If you're not completely satisfied for any reason, simply call Customer Service for a Return Authorization number, and return it within 30 days, and he'll give you a full refund of the purchase price, less shipping and handling, no questions asked.</p>

<p class="price">$119.85</p>
<button><a href="http://teambeachbody.com/shop/-/shopping/T25Base?referringRepId=416555">Buy Now</a></button>


<iframe class="videoWorkout" width="350" height="263"  src="http://www.youtube.com/embed/3---j0igJpQ" frameborder="0" allowfullscreen></iframe>