<h2>Insanity</h2>

<p>Transform your body in 60 days with the most intense workout program ever put on DVD. Shaun T will push you past your limits to get the leanest, hardest body you've ever had.</p>

<p class="bold">60-Day Total-Body Conditioning Program</p>

<p>Your personal trainer Shaun T will push you past your limits with 10 discs packed with cardio and plyometric drills with intervals of strength, power, resistance, and core training. No equipment or weights are needed, and you don’t have to be in extreme shape to do it. As long as you’re ready to dig deep, Shaun will help you get insane results in just 60 days.</p>

<p>Here’s what you get:</p>

<p class="bold">10 Insane Workouts</p>

<ul>
<li><span class="boldTitle">Dig Deeper & Fit Test.</span> To start, Shaun will put your body to the test and see what you're made of. (30 min.)</li>
<li><span class="boldTitle">Plyometric Cardio Circuit.</span> Burn fat with intervals of intense lower-body plyo and sweat-inducing cardio. (42 min.)</li>
<li><span class="boldTitle">Cardio Power & Resistance.</span> Build lean muscle and upper-body definition with strength-training and power moves. (40 min.)</li>
<li><span class="boldTitle">Cardio Recovery.</span> Shaun goes easier on you once a week so you're ready for the next round. (33 min.)</li>
<li><span class="boldTitle">Core Cardio & Balance.</span> Take a break after month 1 and gear up for month 2 with this workout. (37 min.)</li>
<li><span class="boldTitle">Max Interval Circuit & Fit Test. </span> The interval circuit that's more intense than anything you've ever done before. (86 min.)</li>
<li><span class="boldTitle">Max Interval Plyo.</span> Push your legs 'til they beg for mercy with power and plyo, all at your MAX. (55 min.)</li>
<li><span class="boldTitle">Max Cardio Conditioning & Cardio Abs.</span> Get pushed to your limit with this extreme cardio workout. (65 min.)</li>
<li><span class="boldTitle">Max Recovery.</span> Give it a rest and build strength for another round with intense moves and stretches. (47 min.)</li>
</ul>

<p class="bold">Plus, get these 4 free gifts:</p>

<ul>
<li><span class="boldTitle">Elite Nutrition Plan.</span> A food plan specifically designed to fuel your body for these intense workouts.</li>
<li><span class="boldTitle">Fitness Guide. </span> It’s short and to the point, with just the information you need. We want you working out—not reading.</li>
<li><span class="boldTitle">INSANITY® Calendar.</span> Lets you track your progress through Month 1 and Month 2, set workout goals, and stay motivated the whole time. Plus, the Fit Test Tracker tracks your results as you transform your body.</li>
<li><span class="boldTitle">FREE Online Support Tools.</span> Stay inspired with round-the-clock access to fitness experts and peer support.</li>
</ul>

<p class="bold">Bonus workout available on Team Beachbody®:</p>
<ul>
<li><span class="boldTitle">Fast and Furious.</span> When you're short on time, get a 45-minute workout packed into 20 minutes with this bonus INSANITY workout available only on Team Beachbody.</li>
</ul>


<p class="bold">Get insane results, or your money back.</p>
<p>You have a full 60 days to try INSANITY for yourself. If you're not completely satisfied for any reason, simply call Customer Service to return it within 60 days for a full refund of the purchase price, less s&h—no questions asked. </p>

<p class="price">$119.85</p>
<button><a href="http://teambeachbody.com/shop/-/shopping/Insanity?referringRepId=416555">Buy Now</a></button>

<iframe class="videoWorkout" width="350" height="263"  src="http://www.youtube.com/embed/S62uBl49suI" frameborder="0" allowfullscreen></iframe>