<h2>Brazil Butt Lift® Challenge Pack</h2>

<p>Leandro Carvalho, trainer to world-famous supermodels, combines Brazilian dance, cardio, and his own signature lower-body sculpting moves to lift, firm, and shape your behind for a rear view you've always dreamed about.</p>

<p class="bold">Your Challenge Pack also includes:</p>

<ul>
<li>Your first 30-day supply of Shakeology®—the superfood shake that helps give you energy, reduce cravings and accelerate your fitness results—delivered on Home Direct, our monthly autoship program.</li>
<li>A FREE 30-day trial membership in the Team Beachbody® Club, where you'll find all the support you'll need to complete your Challenge.</li>
<li>Plus Super Discount shipping (and SAVE OVER $12) every month</li>
</ul>

<p class="bold">Shape, lift, and firm your booty</p>

<p>The Brazil Butt Lift Challenge Pack combines fat-burning cardio workouts with the best lower-body sculpting moves you've ever tried. Leandro's proven TriAngle Training method works all three major buttocks muscles from multiple angles to help reduce your hips and saddlebags, slim your thighs, and lift your butt without bulking up your thighs.</p>

<p>Here's what your Challenge Pack includes:</p>

<p class="bold">Lift your butt with 6 hot workouts:</p>

<ul>
<li>Booty Basics – Learn proper form for best results. (20 minutes)</li>
<li>Bum Bum – Scorch calories and tighten your booty. (35 minutes)</li>
<li>High & Tight – Focus on your hips and lift your glutes. (35 minute</li>
<li>Sculpt – Tone and shape your entire body. (50 minutes)</li>
<li>Cardio Axe – Burn fat with dance-based cardio. (30 minutes)</li>
<li>Tummy Tuck – Sculpt your flat, sexy abs. (20 minutes)</li>
</ul>

<p class="bold">Plus 5 smart tools:</p>

<ul>
<li><span class="boldTitle">60-DAY BOOTY MAKEOVER GUIDE</span><br />Use the Booty Blueprint to determine your butt type, and get tips for achieving your best booty transformation.</li>
<li><span class="boldTitle">BOOTYLICIOUS MEAL PLAN </span> <br /> This easy-to-follow plan includes zesty, Brazilian-inspired recipes to help you slim down without sacrificing flavor.</li>
<li><span class="boldTitle">TRIANGLE TRAINING WORKOUT CARDS </span> <br />Learn Leandro's signature moves and create your own workout on-the-go.</li>
<li><span class="boldTitle">BOOTY MAKEOVER CALENDAR</span> <br /> Schedule workouts for lifting YOUR butt type.</li>
<li><span class="boldTitle">MEASUREMENT TRACKER and TAPE MEASURE</span> <br />  Track your sexy progress to see your best results.</li>
</ul>


<p class="bold">And 3 FREE bonus gifts:</p>

<ul>
<li><span class="boldTitle">6-DAY SUPERMODEL SLIMDOWN</span><br />Jump-start your booty transformation with the same 6-day plan used by Leandro's supermodel clients before photo shoots.</li>
<li><span class="boldTitle">BOOTY STRENGTH BAND***</span> <br /> Leandro's secret weapon gives an extra boost of lower-body resistance to sculpt those hard-to-reach areas.</li>
<li><span class="boldTitle">BUM BUM RAPIDO</span> <br />This express version of Leandro's trademark workout lifts your butt when you're short on time. (10 mins.)</li>
<li><span class="boldTitle">And FREE online support</span> <br /> Get training, nutrition tips, and amazing support from Leandro and the Brazil Butt Lift community.</li>
</ul>

<p class="bold">Exclusive bonus workout:</p>
<p>Order the Brazil Butt Lift Challenge Pack on TeamBeachbody.com and you'll receive the exclusive bonus workout DVD, Leandro's Secret Weapon. A $19.95 value—FREE!</p>

<p class="bold">PLUS:</p>
<ul>
<li><span class="boldTitle">A 30-Day Supply of Shakeology—The Healthiest Meal of the Day.</span><br />Simplify your nutrition with the convenient and delicious daily superfood protein shake that helps give you energy for your workouts, reduces junk food cravings, and may help you reach your fitness goals faster. A nutrient-dense combination of antioxidants, phytonutrients, adaptogens, and many other rare ingredients gives your body superfoods you can't get from a normal diet. 100% vegan option now available.</li>
</ul>

<p class="bold">PLUS:</p>
<ul>
<li><span class="boldTitle">FREE 30-Day Trial Membership in the Team Beachbody Club.</span><br />
When you're part of the Team Beachbody community, you have all the tools, support, and accountability you need to commit to a healthy lifestyle, including:</li>
<li>10% discount on all purchases</li>
<li>Meal plans personalized for your goals</li>
<li>VIP access to your favorite trainers and Beachbody® experts, including live chats, exclusive videos, nutrition tips, and delicious recipes</li>
<li>Your own personal Coach for guidance and support</li>
<li>Access to SuperGym®, where you can track your progress, work out with your buddies, and meet new friends who share your weight-loss </li>
<li>Message Boards and chat rooms to help you find new friends and workout partners, and get advice and support from the entire community</li>
</ul>

<p class="bold">30-Day Money-Back Guarantee</p>
<p>We're so sure you'll love this Challenge Pack, we're giving you our 30-day money-back guarantee. If you're not completely satisfied, simply call Customer Service to return it within 30 days for a refund of the purchase price (less s&h).</p>


<p class="price">$176.55</p>
<button><a href="http://teambeachbody.com/shop/-/shopping?referringRepId=416555">Buy Now</a></button>

<iframe class="videoWorkout" width="350" height="263" src="http://www.youtube.com/embed/FCLPKAYIb5Y" frameborder="0" allowfullscreen></iframe>