<h2>P90X</h2>

<p>Trainer Tony Horton will transform your body in just 90 days. P90X® is a revolutionary system that constantly introduces new moves to challenge your muscles and give you extraordinary results.</p>

<p class="bold">Get Absolutely Ripped in Just 90 Days</p>

<p>P90X includes 12 sweat-inducing, muscle-pumping workouts, designed to transform your body from regular to ripped in just 90 days. The secret is an advanced training technique called Muscle Confusion™, which accelerates your results by constantly introducing new moves and routines so your body never plateaus.</p>

<p>Here’s what you get with P90X:</p>

<p class="bold">12 Diverse and Intense Workouts:</p>

<ul>
<li><span class="boldTitle">P90X - 01 Chest & Back.</span> Targeted strength and definition workout emphasizes two classic upper-body exercises.</li>
<li><span class="boldTitle">P90X - 02 Plyometrics.</span> Explosive jumping cardio routine, proven to dramatically improve athletic performance.</li>
<li><span class="boldTitle">P90X - 03 Shoulders & Arms.</span> A potent combination of pressing, curling, and fly movements that will leave you stronger and more defined.</li>
<li><span class="boldTitle">P90X - 04 Yoga X.</span> Combines strength, balance, flexibility, and breath work to enhance your physique and calm your mind.</li>
<li><span class="boldTitle">P90X - 05 Legs & Back.</span> Squat, lunge, and pull in a total-body workout like no other.</li>
<li><span class="boldTitle">P90X - 06 Kenpo X.</span> Intense cardiovascular workout includes punching and kicking for endurance, balance, and coordination.</li>
<li><span class="boldTitle">P90X - 07 X Stretch.</span> Achieve a higher level of athleticism, prevent injuries, and avoid plateaus.</li>
<li><span class="boldTitle">P90X - 08 Core Synergistics.</span> Build and support the core while conditioning your body.</li>
<li><span class="boldTitle">P90X - 09 Chest, Shoulders & Triceps.</span> Targeted strength and definition workout emphasizing two classic upper-body exercises.</li>
<li><span class="boldTitle">P90X - 10 Back & Biceps.</span> Flex your powerful biceps, and focus on toning and tightening those showcase upper-body muscles.</li>
<li><span class="boldTitle">P90X - 11 Cardio X.</span> Low-impact, fat-burning cardio routine.</li>
<li><span class="boldTitle">P90X - 12 Ab Ripper X.</span> Sculpt an incredible six-pack and improve your physical performance.</li>
</ul>

<p class="bold">You also get 5 P90X Plus Advanced Workouts (on 4 DVDs):</p>

<ul>
<li><span class="boldTitle">Interval X Plus.</span> Propel your heart rate up and down with 3 speeds: recovery, medium, and full-out, creating the most dramatic change in the shortest period of time.</li>
<li><span class="boldTitle">Kenpo Cardio Plus.</span> This advanced-level Kenpo, with new moves, will shred the most stubborn layer of fat with an all-out self-defense workout.</li>
<li><span class="boldTitle">Upper Plus.</span> This monster upper-body workout will defy the plateau phenomenon by blasting all the muscles from the hips on up.</li>
<li><span class="boldTitle">Total Body Plus.</span> By adding new synergistic moves, your muscles get pumped, then recuperate in stages until you've got nothing left. </li>
<li><span class="boldTitle">Abs/Core Plus.</span> This workout adds 4 different positions (hanging, sitting, standing, and plank positions) to intensify your ab work and shred your midsection even faster.</li>
</ul>

<p class="bold">Plus, get these informative tools:</p>
<ul>
<li><span class="boldTitle">3-Phase Nutrition Plan.</span> Designed to help you lose fat, build lean muscle, and maintain high energy levels through each part of the program.</li>
<li><span class="boldTitle">P90X Fitness Guide.</span> Packed with information and tools to help you set your workout goals, track your progress, and stay inspired.</li>
<li><span class="boldTitle">How to Bring It Video.</span> Get a quick overview of the complete P90X Extreme Home Fitness training system.</li>
</ul>

<p class="bold">And get these tools to keep you motivated:</p>
<ul>
<li>P90X Calendar. Lets you know exactly what to do each day, set your workout goals, track your progress, and stay motivated.</li>
<li>Online Support. You'll have access to Tony and other fitness experts, and peer support from your fellow P90Xers.</li>
</ul>


<p class="bold">Exclusive bonus workouts:</p>
<ul>
<li>Only if you order P90X on Team Beachbody, you will receive 2 workout DVDs from the P90X ONE on ONE™ series. A $40.00 value—FREE!</li>
</ul>

<p class="bold">90-Day Money-Back Guarantee</p>
<p>We’re so sure you'll love this program, we're giving you our 90-day money-back guarantee. If you're not completely satisfied, simply call Customer Service to return P90X within 90 days for a refund of the purchase price, less shipping and handling. But keep the Ab Ripper X routine and the 3-Phase Nutrition Plan as our gift just for trying P90X.</p>

<p class="price">$119.85</p>
<button><a href="http://teambeachbody.com/shop/-/shopping/P90X?referringRepId=416555">Buy Now</a></button>





<iframe class="videoWorkout" width="350" height="263" src="http://www.youtube.com/embed/5VyUs6j54as" frameborder="0" allowfullscreen></iframe>