<h2>P90X3</h2>

<p>Get ripped in 30 minutes a day, using Tony Horton's breakthrough Muscle Acceleration system. Now you'll always have the time to work out—and you can burn fat and build lean muscle faster than ever.</p>

<p class="bold">Get ripped in 30 minutes a day</p>

<p>Feel like there isn't enough time in your jam-packed schedule to work out? Welcome to P90X3's Muscle Acceleration system—your ultimate excuse-buster. Trainer Tony Horton took everything he learned from P90X® and P90X2®, coupled it with new science that shows intense 30-minute workouts can get you in better shape faster, and slammed it all into overdrive. The result? Short, targeted, intense workouts that take just 30 minutes—but leave you looking like you've been tearing it up in the gym all day, every day.</p>

<p>Your P90X3 program includes:</p>

<p class="bold">16 extreme 30-minute workouts:</p>

<p>Resistance Workouts:</p>

<ul>
<li><span class="boldTitle">Total Synergistics.</span> A full-body resistance workout that triggers fast, powerful changes to your body's composition.</li>
<li><span class="boldTitle">The Challenge. </span> Strengthen your entire upper body by stacking push-ups and pull-ups in ways you've probably never seen.</li>
<li><span class="boldTitle">Incinerator. </span> Bring It 'til there's nothing left to bring. A full burnout session that pushes you past your limits.</li>
<li><span class="boldTitle">Eccentric Upper.</span> Time under tension is the key to creating lean-muscle growth fast. This upper-body blast will have you begging for mercy.</li>
<li><span class="boldTitle">Eccentric Lower.</span> You'll be slowing down the eccentric (or negative) half of each movement to carve a ripped lower body—faster.</li>
<li><span class="boldTitle">The Warrior.</span> When you need a one-size-fits-all workout that can be done anytime, anywhere, this is your drill.</li>
</ul>

<p>Power Workouts:</p>

<ul>
<li><span class="boldTitle">Agility X.</span> This fusion of aerobic and anaerobic energy improves your precision, flexibility, balance, and strength.</li>
<li><span class="boldTitle">Triometrics.</span> Increase your speed and power in a fraction of the time with this explosive next-generation plyo workout.</li>
<li><span class="boldTitle">Decelerator.</span> Balance your ability to go up strong and come down safe with multi-angle deceleration training.</li>
</ul>

<p>Cardio Workouts:</p>
<ul>
<li><span class="boldTitle">CVX.</span> Now resistance is combined with intervals to give you that full-body burn and power up your core.</li>
<li><span class="boldTitle">MMX. </span> Burn fat by taxing your strength, endurance, and flexibility with this martial arts–based cardio workout.</li>
<li><span class="boldTitle">Accelerator. </span> Increase your cardiovascular and muscular efficiency, resulting in more bang for your fat-burning buck.</li>
</ul>


<p>Core, Flexibility & Balance Workouts:</p>
<ul>
<li><span class="boldTitle">X3 Yoga.</span>A flow-style practice that improves your musculoskeletal flexibility, balance, stamina, and core strength.</li>
<li><span class="boldTitle">Pilates X. </span> Power your core, gain muscle elasticity, and stabilize your joints, as Pilates fundamentals meet modern science.</li>
<li><span class="boldTitle">Isometrix. </span> Isometric contraction combined with instability—this workout gives you an unshakable platform to work from.</li>
<li><span class="boldTitle">Dynamix. </span> Increase your range of motion, flexibility, and stabilization to help maximize the results you get from every routine.</li>
</ul>

<p>Plus, 5 Free Gifts:</p>
<ul>
<li><span class="boldTitle">Fitness Guide.</span> Your step-by-step guide to getting the most out of Tony's accelerated extreme fitness program.</li>
<li><span class="boldTitle">Nutrition Guide.</span> A simplified approach to healthy eating designed to get you ripped—and help you stay that way.</li>
<li><span class="boldTitle">P90X3 Workout Calendar.</span> Tony gives you each day's workout, so all you have to do is get in—and crush it.</li>
<li><span class="boldTitle">"How to Accelerate" DVD.</span> This easy-to-follow P90X3 intro shows you how to achieve your best results in the fastest time.</li>
<li><span class="boldTitle">24/7 Online Support. </span> Stay motivated with exclusive 'round-the-clock access to fitness experts and peer support.</li>
</ul>

<p>And a FREE Bonus Workout:</p>
<ul>
<li><span class="boldTitle">On One Leg.</span> It's an entire workout on only one leg! Just when you thought you had seen it all from the Master of Muscle Confusion™, he comes at you hard with a little twist. A $19.95 value—FREE when you order P90X3 through your Coach or Team Beachbody®.</li>
</ul>

<p class="bold">90-Day Money-Back Guarantee</p>
<p>Tony's so sure you'll get ripped in 30 minutes a day with P90X3, he's giving you a 90-day money-back guarantee. If you're not completely satisfied for any reason, simply call Customer Service for a Return Authorization number, and return it within 90 days, and he'll give you a full refund of the purchase price, less shipping and handling, no questions asked.</p>

<p class="price">$119.85</p>
<button><a href="http://teambeachbody.com/shop/-/shopping/X3Base?referringRepId=416555">Buy Now</a></button>

<iframe class="videoWorkout" width="350" height="263" src="http://www.youtube.com/embed/KT0lzSM7XQU" frameborder="0" allowfullscreen></iframe>