<h2>P90X2</h2>

<p>Train off-balance to build the body of an athlete. Using a breakthrough in sports science called Muscle Integration, P90X2® delivers pro-level results in just 90 days.</p>

<p class="bold">Get blown away by your visible results. AND performance.</p>

<p>P90X2 delivers the kind of results pro athletes insist on with a breakthrough in applied sports science called Muscle Integration. With P90X2, you'll do resistance moves on one foot, a ball, or some other unstable platform, forcing your body to fire an entire chain of muscles in order to maintain stability.</p>

<p>Here’s what you get with P90X:</p>

<p class="bold">12 breakthrough, muscle-challenging workouts:</p>

<ul>
<li><span class="boldTitle">X2 Core.</span> Works your core using instability. Master this routine for overall improved movement.</li>
<li><span class="boldTitle">Plyocide.</span> Explosive movements combined with mind and coordination drills for super speed/endurance.</li>
<li><span class="boldTitle">X2 Recovery + Mobility. </span> Realign your body with a foam-rolling technique and complete stretching routine.</li>
<li><span class="boldTitle">X2 Total Body.</span> Push your body to use the correct muscles and proper form to handle resistance and instability challenges.</li>
<li><span class="boldTitle">X2 Yoga.</span> Increase your isometric power and range of motion, and build stabilizer muscle strength.</li>
<li><span class="boldTitle">X2 Balance + Power.</span> Push your limits through strength and explosive movements while improving alignment.</li>
<li><span class="boldTitle">Chest + Back + Balance.</span> AAchieve superior strength gains over those achieved through traditional weight training by working on unstable platforms.</li>
<li><span class="boldTitle">X2 Shoulders + Arms.</span> Keep your shoulders and arms strong and in balance to help minimize your risk of injury.</li>
<li><span class="boldTitle">Base + Back.</span> Give your two largest muscle groups a super workover with a pull-up and plyo extravaganza.</li>
<li><span class="boldTitle">P.A.P. Lower.</span> Give your lower body a cutting-edge workout with four-round complexes that boost performance.</li>
<li><span class="boldTitle">P.A.P. Upper.</span> Regain your youth with Post-Activation Potentiation training for your upper body.</li>
<li><span class="boldTitle">X2 Ab Ripper. </span> Upgrade your concept of what an ab workout should be with a series of demanding core movements.</li>
</ul>

<p class="bold">Plus, get these information-loaded tools:</p>

<ul>
<li><span class="boldTitle">Fitness Guide.</span> Get all the facts and tools you need to maximize your P90X2 results.</li>
<li><span class="boldTitle">Nutrition Guide.</span> We've evolved the diet along with the exercise program. Now in addition to traditional high-performance food choices, you can customize your plan with grain-free and vegan options.</li>
<li><span class="boldTitle">How to Bring It Again Video.</span> Get a quick overview of the complete P90X2 training system.</li>

</ul>

<p class="bold">And even more tools to keep you on track:</p>
<ul>
<li><span class="boldTitle">90-Day Workout Calendar.</span> Set P90X2 workout goals each day, and schedule your recovery week when you need it.</li>
<li><span class="boldTitle">Online Support. </span> You'll have access to Tony Horton and our panel of Beachbody® experts as well as peer support from other people doing P90X2.</li>
</ul>


<p class="bold">Exclusive bonus workouts:</p>
<ul>
<li>Get 2 FREE workouts when you order from your Coach or Team Beachbody®: P90X ONE on ONE® 4 Legs and P90X ONE on ONE® Upper Body Balance. A $39.90 value—FREE.</li>
</ul>

<p class="bold">90-Day Money-Back Guarantee</p>
<p>We're so sure you'll love this program, we're giving you our 90-day money-back guarantee. If you're not completely satisfied, simply call Customer Service to return P90X2 within 90 days for a refund of the purchase price.</p>

<p class="price">$119.85</p>
<button><a href="http://teambeachbody.com/shop/-/shopping/X2-BasereferringRepId=416555">Buy Now</a></button>

<iframe width="350" class="videoWorkout" height="263" src="http://www.youtube.com/embed/6DuDPzFYswM" frameborder="0" allowfullscreen></iframe>